spring.application.name=smart-budget-backend

# Подключение к БД
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/smart_budget}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:mySuperSecretKeyForJWTGenerationWithAtLeast32BytesLong!}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Настройки сервера
server.port=8080